## Linear Regression Multiple Variables Exercise

### Description

In exercise folder (same level as this notebook on github) there is hiring.csv. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,

2 yr experience, 9 test score, 6 interview score

12 yr experience, 10 test score, 10 interview score

In [2]:
pip install word2number

  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5591 sha256=103ad79b59032307ad745370616aa8c64e2586ad7a06636fe811e23029a6cb75
  Stored in directory: c:\users\csris\appdata\local\pip\cache\wheels\cb\f3\5a\d88198fdeb46781ddd7e7f2653061af83e7adb2a076d8886d6
Successfully built word2number
Note: you may need to restart the kernel to use updated packages.


In [11]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [12]:
hiring = pd.read_csv('hiring.csv')
hiring.head(10)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [14]:
hiring.experience = hiring.experience.fillna('zero')
hiring

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [19]:
import math
hiring['test_score(out of 10)'] = hiring['test_score(out of 10)'].fillna(math.floor(hiring['test_score(out of 10)'].mean()))
hiring

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    7.0                           7      72000
7     eleven                    7.0                           8      80000

In [20]:
hiring.experience = hiring.experience.apply(w2n.word_to_num)
hiring

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [21]:
reg = linear_model.LinearRegression()
reg.fit(hiring[['experience','test_score(out of 10)','interview_score(out of 10)']],hiring['salary($)'])

LinearRegression()

In [22]:
reg.predict([[2,9,6]])

array([53713.86677124])

In [23]:
reg.predict([[12,10,10]])

array([93747.79628651])

## Generate CSV file

In [24]:
p = reg.predict(hiring[['experience','test_score(out of 10)','interview_score(out of 10)']])
p

array([52090.46734071, 45648.01964161, 57964.2290839 , 64525.1061363 ,
       68325.21184635, 60783.44785255, 74796.8832586 , 79866.63483999])

In [25]:
hiring['salary($)']=p

In [26]:
hiring

experience  test_score(out of 10)  interview_score(out of 10)     salary($)
0           0                    8.0                           9  52090.467341
1           0                    8.0                           6  45648.019642
2           5                    6.0                           7  57964.229084
3           2                   10.0                          10  64525.106136
4           7                    9.0                           6  68325.211846
5           3                    7.0                          10  60783.447853
6          10                    7.0                           7  74796.883259
7          11                    7.0                           8  79866.634840

In [ ]:
new_df.to_csv("prediction.csv")